export const MAKE_CONTACT = 'MAKE_CONTACT'
export const NOTIFY = 'NOTIFY'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'


export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const ADICIONA_TAREFAS = 'ADICIONA_TAREFAS'
export const ALTERA_TAREFAS = 'ALTERA_TAREFAS'
export const NOTIFICAR = 'NOTIFICAR'